version: "3.9"
services:
  mysql-db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      TZ: Asia/Jakarta
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pwd}
      MYSQL_USER: ${MYSQL_USER:-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-pwd}
    restart: unless-stopped
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root --password=${MYSQL_ROOT_PASSWORD:-pwd}"]
      interval: 0.5s
      timeout: 10s
      retries: 10
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS invoice-item-service;' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD:-pwd}
    ports:
      - 9200:9200
      - 9300:9300
    restart: unless-stopped
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200/_cluster/health?pretty || exit 1"]
      interval: 10s
      retries: 5
      start_period: 30s

volumes:
  esdata:
